// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOZEQOmY0ZRExNM9CXZKQlI4DYEjK4QbE',
    appId: '1:25260154780:web:ee542f15175ccfe4613259',
    messagingSenderId: '25260154780',
    projectId: 'courseselect-4068c',
    authDomain: 'courseselect-4068c.firebaseapp.com',
    storageBucket: 'courseselect-4068c.appspot.com',
    measurementId: 'G-XPNSBPQ9NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfK76ktp0fI-NPBMkFh20BSqqiINIbbJk',
    appId: '1:25260154780:android:d58744188b3b466f613259',
    messagingSenderId: '25260154780',
    projectId: 'courseselect-4068c',
    storageBucket: 'courseselect-4068c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs19RMgfsZS9tHp1nZ_lBql18C0KhqpS4',
    appId: '1:25260154780:ios:7c4712800dc6ed78613259',
    messagingSenderId: '25260154780',
    projectId: 'courseselect-4068c',
    storageBucket: 'courseselect-4068c.appspot.com',
    iosClientId: '25260154780-8f8u5jr6df8k3r49d3a45o5lb2n333v9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs19RMgfsZS9tHp1nZ_lBql18C0KhqpS4',
    appId: '1:25260154780:ios:7c4712800dc6ed78613259',
    messagingSenderId: '25260154780',
    projectId: 'courseselect-4068c',
    storageBucket: 'courseselect-4068c.appspot.com',
    iosClientId: '25260154780-8f8u5jr6df8k3r49d3a45o5lb2n333v9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
